import { NextResponse } from "next/server";
import { eq } from "drizzle-orm";
import { db, schema } from "@/db/client";
import { getCurrentContext } from "@/lib/auth/devUser";
import { assertEditable, getInterviewForOrg } from "@/lib/api/interviewAccess";
import { handleApiError, notFound, badRequest } from "@/lib/api/errors";
import { regenerateSingleQuestion } from "@/lib/ai/generateQuestions";
import { recordAiUsage } from "@/lib/api/usage";
import { MODELS } from "@/lib/ai/anthropic";

export async function POST(
  _req: Request,
  ctx: { params: Promise<{ id: string; questionId: string }> },
) {
  try {
    const { org } = await getCurrentContext();
    const { id, questionId } = await ctx.params;
    const { interview, profile, questions } = await getInterviewForOrg(id, org.id);
    assertEditable(interview);

    const targetIndex = questions.findIndex((q) => q.id === questionId);
    if (targetIndex < 0) notFound("Question not found.");
    if (questions[targetIndex].category === "custom") {
      badRequest("Custom questions are not regenerated by the model.");
    }

    const { question, usage } = await regenerateSingleQuestion(
      {
        title: profile.title,
        level: profile.level,
        responsibilities: profile.responsibilities,
        requiredSkills: profile.requiredSkills,
        niceToHaves: profile.niceToHaves,
        roleContext: profile.roleContext,
        successCriteria: profile.successCriteria,
      },
      questions.map((q) => ({
        orderIndex: q.orderIndex,
        text: q.text,
        category: q.category as "behavioral" | "technical" | "situational" | "motivation_fit",
        timeLimitSeconds: q.timeLimitSeconds,
        retryAllowed: q.retryAllowed,
        rationale: q.rationale ?? "",
      })),
      targetIndex,
    );

    const [row] = await db
      .update(schema.interviewQuestions)
      .set({
        text: question.text,
        timeLimitSeconds: question.timeLimitSeconds,
        retryAllowed: question.retryAllowed,
        rationale: question.rationale,
      })
      .where(eq(schema.interviewQuestions.id, questionId))
      .returning();

    await recordAiUsage({
      orgId: org.id,
      interviewId: interview.id,
      model: MODELS.questions(),
      inputTokens: usage.input,
      outputTokens: usage.output,
    });

    return NextResponse.json({ question: row });
  } catch (err) {
    return handleApiError(err);
  }
}
